In [2]:
import numpy as np

In [34]:
def spherical_func(X, X0=np.array([0, 0])):
    return np.sum(np.power(X - X0, 2))

spherical_func(np.array([2, 2]), np.array([0, 2]))

4

In [50]:
def initialize_X(SN, Xmin, Xmax, func):
    if Xmin.shape != Xmax.shape:
        raise ValueError('initialize_X: Xmin.shape != Xmax.shape')
    X = np.zeros((SN, Xmin.shape[0]))
    FX = np.zeros(SN)
    for i in range(SN):
        X[i] = Xmin + np.random.uniform(0, 1, Xmin.shape[0])*(Xmax - Xmin)
        FX[i] = func(X[i])
    return X, FX

def employed_phase(X, FX, func):
    V = np.zeros(X.shape)
    FV = np.zeros(X.shape[0])
    for i in range(X.shape[0]):
        k = np.random.randint(X.shape[0] - 1)
        if k >= i:
            k += 1
        V[i] = X[i] + np.random.uniform(-1., 1.)*(X[i] - X[k])
        FV[i] = func(V[i])
    for i in range(X.shape[0]):
        if FV[i] < FX[i]:
            X[i] = V[i]
            FX[i] = FV[i]
    return X, FX

def onlooker_phase(X, FX, func):
    def fit(f):
        return 1./(1+f) if f >= 0 else 1 + np.abs(f)
    
    fitX = np.vectorize(fit)(FX)
    idx_selected = np.random.choice(
        X.shape[0],
        p=fitX/np.sum(fitX)
    )
    X_selected = X[idx_selected].copy()
    
    V = np.zeros(X.shape)
    FV = np.zeros(X.shape[0])
    for i in range(X.shape[0]):
        k = np.random.randint(X.shape[0] - 1)
        if k >= i:
            k += 1
        V[i] = X[i] + np.random.uniform(-1., 1.)*(X[i] - X_selected)
        FV[i] = func(V[i])
    for i in range(X.shape[0]):
        if FV[i] < FX[i]:
            X[i] = V[i]
            FX[i] = FV[i]
    return X, FX

Xmin = np.array([0., 0.])
Xmax = np.array([1., 2.])

X, FX = initialize_X(5, Xmin, Xmax, spherical_func)
print(X)
print(FX)
print('=====================')
X, FX = employed_phase(X, FX, spherical_func)
print(X)
print(FX)
print('=====================')
X, FX = onlooker_phase(X, FX, spherical_func)
print(X)
print(FX)
print('=====================')

[[0.09960142 1.02863931]
 [0.50631339 1.58633232]
 [0.53097729 1.63650633]
 [0.72871443 0.08284185]
 [0.0768794  1.42219428]]
[1.06801928 2.77280346 2.96008987 0.5378875  2.02854701]
[[0.09960142 1.02863931]
 [0.50631339 1.58633232]
 [0.51989448 1.61396046]
 [0.72871443 0.08284185]
 [0.0768794  1.42219428]]
[1.06801928 2.77280346 2.87515864 0.5378875  2.02854701]
[[0.09960142 1.02863931]
 [0.20255952 1.16981787]
 [0.51989448 1.61396046]
 [0.72871443 0.08284185]
 [0.0982159  1.05263718]]
[1.06801928 1.40950421 2.87515864 0.5378875  1.11769139]
